### ISSUE TITLE
Vue3 Typescript not working

### ISSUE THREAD

**Issue by sadortun** [davestewart/vue-class-store#18]
Hi,

Is it me or i'm missing something here  `package.json` revers to a `.ts` which does not exists

https://github.com/davestewart/vue-class-store/blob/feature/vue-3/package.json#L8

And your build script generates a `.js`

https://github.com/davestewart/vue-class-store/blob/master/build/rollup.js#L65

Thanks

**Comment by davestewart** [comment]
Hmm. It's a been a while since I looked at this!

Is it broken?

What happens if you change that line to `.js` manually?

**Comment by sadortun** [comment]
> What happens if you change that line to .js manually?

It works !

**Comment by davestewart** [comment]
OK, I'll take a look. Thanks!
