### ISSUE TITLE
create a factory function so classes can be used not only in components

### ISSUE THREAD

**Issue by digi604** [davestewart/vue-class-store#4]

**Comment by davestewart** [comment]
Hi Patrick.

I don't think I understand your request.

You can use Vue Class Store anywhere.

What seems to be the problem?

Can you provide a code example?

**Comment by digi604** [comment]
Sure for a global store you currently use:

`export default {
  provide () {
    return {
      $products: new ProductsStore()
    }
  },
}`

now this single instance of $products is now available in all the components but not in other classes or js functions. To make this work the composition API comes to mind. 

`
const useProductStore = createNewStore(new ProductsStore())
`

now createNewStore returns a function that always returns the same instance of ProductStore() so you can use it anywhere with:
`
const store = useProductStore()
`

**Comment by davestewart** [comment]
Ah, I see.

Do you not think this would be best handled by the individual developer?

It should be as easy as exporting a store from `@/store/index.ts`.

**Comment by digi604** [comment]
export const useProductStore = createNewStore(new ProductsStore())

**Comment by davestewart** [comment]
OK. Thanks for the clarification.

Closing this as I think users should handle store instantiation themselves.
